### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by Kalovelo** [aeternity/aepp-faucet-nodejs#13]
I think there needs to be a CORS configuration.

```
axios.post("https://faucet-nodejs.prd.aepps.com/account/ak_GfXpfpwouMpUjxmRxVApPueRozecXnuwXHaN8duEUWu9fSzUA", {})
```
results in a cors error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://faucet-nodejs.prd.aepps.com/account/ak_GfXpfpwouMpUjxmRxVApPueRozecXnuwXHaN8duEUWu9fSzUA. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

Even if the funding takes place, it's still harder to debug and check it since it will throw an error any way

You will get a similar error if you open your browser's console and execute

```
fetch("https://faucet.aepps.com/account/ak_GfXpfpwouMpUjxmRxVApPueRozecXnuwXHaN8duEUWu9fSzUA",{
method:"POST"})
```

**Comment by marc0olo** [comment]
@mmpetarpeshev can this be solved from your side?

wondering what's different now compared to the previous deployment 🤔

**Comment by mmpetarpeshev** [comment]
Which previous deployment ? We didn't change anything on the infra side . 
What headers should be allowed ?

**Comment by Kalovelo** [comment]
This is could be done on application level see

- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_response_headers
- https://expressjs.com/en/resources/middleware/cors.html

**Comment by mmpetarpeshev** [comment]
Yes , it should be firstly done there.
