### ISSUE TITLE
hosting / replacement of old python faucet

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-faucet-nodejs#9]
@dincho @mmpetarpeshev this topic becomes more urgent recently due to the state channel demo we wanna present.

my assumption is that still the old Python faucet is deployed at https://faucet.aepps.com - can you confirm that?

the problem is we will probably have many people simultaneously trying to fund their wallets with the faucet when playing around with that demo. I assume there is an error in the nonce-handling right now.

we should:
- deploy nodejs faucet
- fix nodejs faucet to be able to handle many requests simultaneously and use the right nonce **(if needed)**
    - I know there is a feature in the node now to return the correct nonce based on what tx's are known in the mempool to avoid re-usage and fill gaps. this probably may not work if node is behind loadbalancer, right?! cc @velzevur 

cc: @davidyuk @velzevur @Kalovelo

is it possible we can achieve that in the upcoming weeks before the conference?

_Originally posted by @marc0olo in https://github.com/aeternity/aepp-faucet-nodejs/issues/8#issuecomment-1220634651_

**Comment by marc0olo** [comment]
@mmpetarpeshev if we have it deployed in the k8s environment and accessible there we could just point to that URL. then the switch of the main-url wouldn't be that urgent of course.

but for fixing issues in this faucet here we should have auto-deployment enabled in case we need to fix sth.

**Comment by marc0olo** [comment]
just remembered about https://faucet.dev.aepps.com where this repo is deployed, right?

are we using the same account as on https://faucet.aepps.com ?

what's definitely important to know is if the old python faucet is still deployed or whether it's this nodejs version.

and if we use same account for both faucets deployments it might not be sufficient to just use https://faucet.dev.aepps.com instead of https://faucet.aepps.com to fix the nonce-handling

**Comment by marc0olo** [comment]
not sure why I closed this

**Comment by marc0olo** [comment]
@mmpetarpeshev I think we can close this now, right? has the old python faucet been taken down now?

**Comment by mmpetarpeshev** [comment]
I don't think so , Dincho is off this week , so maybe next one he can do that, if it's required.

**Comment by marc0olo** [comment]
alright. but https://faucet.aepps.com now points to the nodejs version, right?

@dincho let me know once taken down. will happily archive the old faucet repo finally ....

**Comment by mmpetarpeshev** [comment]
Correct , it points to the nodejs.

**Comment by marc0olo** [comment]
I think we can close it 😅 👀
